### ISSUE TITLE
Create config output for playground

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-forgae-js#106]
Hey, it would be cool to easily use playground with forgae's dev net and its accounts. Why not output a config for playground to do all this? Both as file and maybe copy-paste from console output.

**Comment by thepiwo** [comment]
@maptuhec was there an update about this?

**Comment by maptuhec** [comment]
Hey @thepiwo @nikita-fuchs  currently, we don't have any progress or update on this. All of the accounts are available from the console when starting the node, the compiler port is also available. We can add information about the node. This is will be pretty easy. About extracting them into a file, we can create an issue and plan it for sprint 44.
