### ISSUE TITLE
forgAE on windows (docker and network)

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-forgae-js#130]
I just tried to run forgAE again on windows with docker-toolbox.

When using `forgae node` too bootstrap the network I get the following error:
```
$ forgae node
error: 'Error: Command failed: docker   ps
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: Das System kann die angegebene Datei nicht finden. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
' stdout = '' stderr = 'error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.37/containers/json: open //./pipe/docker_engine: Das System kann die angegebene Datei nicht finden. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
'
```

This can easily be solved by just starting the network via `docker-compose up -d`.

The biggest pain is that it doesn't seem to be possible to configure the **network url** for the compilation of the contract. So currently we can only choose between:
- local
- testnet
- mainnet

I need to explicitly be able to change the URL or define a specific URL forgAE is trying to use for compilation.

When I use docker-toolbox on windows my node is reachable under `192.168.99.100:3001`.

**Comment by marc0olo** [comment]
For people that do not want to install docker on windows but still use docker-toolbox you should add some notes to the README.

And it must be possible to specify a certain endpoint where the local nodes are reachable.

At least that is what I would expect =)

**Comment by maptuhec** [comment]
Hey @marc0olo,

You are right on the two topics here. We will not support docker toolbox because is a legacy way of using docker for desktop, but you are right and we will describe this in the documentation. Thanks for the feedback on this.

About the configurable network, this is something that we have discussed and will implement, so stay tuned about this functionality.

Martin

**Comment by marc0olo** [comment]
That's fine. I already switch from docker toolbox to docker on windows now.
