### ISSUE TITLE
Add local compiler to forgae

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-forgae-js#144]
Add local compiler in the docker compose, so when we start the node we can start also on compiler.

**Comment by maptuhec** [comment]
This can be checked together witch Nikita, because yesterday a CLI compiler was released, and probably integration with it will be better

**Comment by thepiwo** [comment]
@maptuhec a cli compiler couldn't be used by http services, e.g. samples provided by the shape

**Comment by maptuhec** [comment]
@thepiwo we have dropped out the idea of the cli compiler, currently implementing the standalone compiler with the docker files
