### ISSUE TITLE
Allow tests to (optionally) be written in sophia

### ISSUE THREAD

**Issue by thepiwo** [aeternity/aepp-forgae-js#155]
Some functionality of sophia can't be used via the http api that a developer may want to test, e.g. passing functions as arguments. Therefore I propose to make an interface that allows tests to be written in sophia.

**Comment by thepiwo** [comment]
where can I find some documentation on how to use this?

**Comment by maptuhec** [comment]
@thepiwo currently you can check it from here: https://github.com/aeternity/aepp-forgae-js/blob/develop/doc/developer-documentation/forgae-cli/testing.md

The documentation in gitbook is not yet updated with this, it will be in the next few days.
