### ISSUE TITLE
Deploy with compiler options.

### ISSUE THREAD

**Issue by kraikov** [aeternity/aepp-forgae-js#167]
When I try to `deploy` using my own compiler, forgae still uses the ACI from the local one.

![Screenshot from 2019-05-24 16-31-26](https://user-images.githubusercontent.com/7030722/58331862-b0c2ab80-7e42-11e9-9f07-26d3dc29fcfa.png)

**Comment by alekseytsekov** [comment]
@kraikov can you provide more info like smart contract and deployment script

**Comment by maptuhec** [comment]
@kraikov is this still an issue, or we can close it ?

**Comment by maptuhec** [comment]
I will close the issue
