### ISSUE TITLE
Issues when deploying contracts with records 

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-forgae-js#168]
Getting the following error while trying to deploy a contracts that has a type record in it>

```Error: TypeError: record is not iterable```

Here is an example contract that can be used for testing:
https://github.com/thepiwo/aepp-todolist/blob/master/contracts/todo-list.aes

**Comment by snaphuman** [comment]
Hello!

¿Does this issue has been resolved in version 2.0.1?

I have updated my env from forgAE 1.3.2 to 2.0.1, updated node_modules and reinitialized the project. 
From the command line It compiles the contract and shows the bytecode, however, when running the deploy operation it returns `Error: TypeError: record is not iterable  `

I have tested the contract in https://testnet.contracts.aepps.com/ and deploys successfully
When using the local contracts aepp the deployment fails with:  `Error: While calling postTransaction (body), POST to http://localhost:3002/v2/transactions failed with 400: Invalid tx `

Thank you
