### ISSUE TITLE
I've got this error when installing forgae "npm i -g forgae"

### ISSUE THREAD

**Issue by GoodnessEzeokafor** [aeternity/aepp-forgae-js#193]

**Comment by GoodnessEzeokafor** [comment]
C:\Users\goote_000\Documents\smart_contracts\aepp-contracts\node_modules\argon2>
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\n
pm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node
-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_mo
dules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\goote_000\AppData\Local\Programs\
Python\Python37-32\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info
[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:259:5)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\goote_000\Documents\smart_contracts\aepp-contracts\node_mo
dules\argon2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is
installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goote_000\AppData\Roaming\npm-cache\_logs\2019-06-15T00_22
_13_396Z-debug.log

**Comment by maptuhec** [comment]
@GoodnessEzeokafor  Hey there, can you share with us what version of python and nodejs are you using? Also, what is the OS that you are using?

Thanks

**Comment by GoodnessEzeokafor** [comment]
windows 8.1 Pro 64-bit Operating System, x64-based processor
python3.7
node 10.16.0

**Comment by thepiwo** [comment]
@maptuhec is there an update on this?

**Comment by maptuhec** [comment]
@GoodnessEzeokafor Do you still experience this issue? If yes we will investigate and come back asap. Sorry for the dely

**Comment by GoodnessEzeokafor** [comment]
C:\Users\goote_000\Documents\smart_contracts\contracts>npm install @aeternity/ae
pp-sdk

> argon2@0.19.3 install C:\Users\goote_000\Documents\smart_contracts\contracts\n
ode_modules\argon2
> node-gyp rebuild


C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules\argon2>if no
t defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\no
de_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.
js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules
\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules\argon2\buil
d\libargon2.vcxproj(20,3): error MSB4019: The imported project "C:\Microsoft.Cp
p.Default.props" was not found. Confirm that the path in the <Import> declarati
on is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\goote_000\Documents\smart_contracts\contracts\node_modules
\argon2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\goote_000\Docu
ments\smart_contracts\contracts\package.json'
npm WARN contracts No description
npm WARN contracts No repository field.
npm WARN contracts No README data
npm WARN contracts No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goote_000\AppData\Roaming\npm-cache\_logs\2019-07-10T22_42
_04_453Z-debug.log

C:\Users\goote_000\Documents\smart_contracts\contracts>

**Comment by GoodnessEzeokafor** [comment]
yes i do

**Comment by GoodnessEzeokafor** [comment]
C:\Users\goote_000\Documents\smart_contracts\contracts>npm i -g forgae
C:\Users\goote_000\AppData\Roaming\npm\forgae -> C:\Users\goote_000\AppData\Roam
ing\npm\node_modules\forgae\forgae-cli.js

> argon2@0.19.3 install C:\Users\goote_000\AppData\Roaming\npm\node_modules\forg
ae\node_modules\argon2
> node-gyp rebuild


C:\Users\goote_000\AppData\Roaming\npm\node_modules\forgae\node_modules\argon2>i
f not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\np
m\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_mod
ules\node-gyp\bin\node-gyp.js" rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
C:\Users\goote_000\AppData\Roaming\npm\node_modules\forgae\node_modules\argon2\
build\libargon2.vcxproj(20,3): error MSB4019: The imported project "C:\Microsof
t.Cpp.Default.props" was not found. Confirm that the path in the <Import> decla
ration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:248:12)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\goote_000\AppData\Roaming\npm\node_modules\forgae\node_mod
ules\argon2
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\for
gae\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! argon2@0.19.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the argon2@0.19.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\goote_000\AppData\Roaming\npm-cache\_logs\2019-07-10T22_50
_57_070Z-debug.log

C:\Users\goote_000\Documents\smart_contracts\contracts>
C:\Users\goote_000\Documents\smart_contracts\contracts>

**Comment by GoodnessEzeokafor** [comment]
VCBUILD : error : project file 'C:\Users\goote_000\AppData\Roaming\npm\node_mod
ules\forgae\node_modules\argon2\build\libargon2.vcproj' was not found or not a
valid project file. [C:\Users\goote_000\AppData\Roaming\npm\node_modules\forgae
\node_modules\argon2\build\binding.sln]

any idea on how to fix that

**Comment by GoodnessEzeokafor** [comment]
Jeez!!!!!!!!!!!!!! 
i finally installed it
thanks alot

**Comment by maptuhec** [comment]
@GoodnessEzeokafor Can you share with us what was the solution, so we can put it in our documentation for future users? thanks in advance

**Comment by GoodnessEzeokafor** [comment]
//PowerShell as administrator
npm install --global --production windows-build-tools

// The for npm
npm config set msvs_version 2015 --global


// Or then for YARN
yarn config set msvs_version 2015 --global

// One of the major error i encountered was Microsoft.Cpp.Default.props was not found, which is caused when the microsoft visual studio(or its variation) is not installed or the VCTargetsPath is not properly configured
// i tried to look for the Microsoft.Cpp.Default.props folder online i saw te folder is usally located at
//For Visual studio 2015: drive:\Program Files (x86)\MSBuild\Microsoft.Cpp (x86)\v4.0\v140\
//For Visual studio 2017: drive:\Program Files (x86)\Microsoft Visual Studio\year\edition\Common7\IDE\VC\VCTargets\

// i fixed it by forcing the installation/update of the Microsoft Visual Studio manually through the window build tools package

* So First i located the package which is usually in C:\Users\%USERNAME%\.windows-build-tools and ran the vs_build.exe inside
* Then i configured the VCTargetsPath
    * Type regdit in windows search
    * Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0
    * Create/update string value key VCTargetsPath and set it to $(MSBuildExtensionsPath32)\Microsoft.Cpp\v4.0\ for Windows Studio 2015
    * Create/update string value key VCTargetsPath and set it to $(MSBuildExtensionsPath32)\IDE\VC\VCTargets\
    its also important to know your MSBUILDExtensionsPath32 is
    Windows Default:
        MSBuildExtensionsPath = C:\Program Files (x86)\MSBuild
        MSBuildExtensionsPath32 = C:\Program Files (x86)\MSBuild
        MSBuildExtensionsPath64 = C:\Program Files\MSBuild
    i changed mine tho MSBuildExtensionsPath32=C:\Program Files (x86)\Microsoft Visual Studio\year\edition\Common7

**Comment by GoodnessEzeokafor** [comment]
My AE Address: ak_2Hjzq1jBw2cYmQjqcfNRU29JFHQMwo5iBqxKRe2fM3PWPiMUti to collect the bounty
//PowerShell as administrator
npm install --global --production windows-build-tools

// The for npm
npm config set msvs_version 2015 --global


// Or then for YARN
yarn config set msvs_version 2015 --global

// One of the major error i encountered was Microsoft.Cpp.Default.props was not found, which is caused when the microsoft visual studio(or its variation) is not installed or the VCTargetsPath is not properly configured
// i tried to look for the Microsoft.Cpp.Default.props folder online i saw te folder is usally located at
//For Visual studio 2015: drive:\Program Files (x86)\MSBuild\Microsoft.Cpp (x86)\v4.0\v140\
//For Visual studio 2017: drive:\Program Files (x86)\Microsoft Visual Studio\year\edition\Common7\IDE\VC\VCTargets\

// i fixed it by forcing the installation/update of the Microsoft Visual Studio manually through the window build tools package

* So First i located the package which is usually in C:\Users\%USERNAME%\.windows-build-tools and ran the vs_build.exe inside
* Then i configured the VCTargetsPath
    * Type regdit in windows search
    * Navigate to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0
    * Create/update string value key VCTargetsPath and set it to $(MSBuildExtensionsPath32)\Microsoft.Cpp\v4.0\ for Windows Studio 2015
    * Create/update string value key VCTargetsPath and set it to $(MSBuildExtensionsPath32)\IDE\VC\VCTargets\
    its also important to know your MSBUILDExtensionsPath32 is
    Windows Default:
        MSBuildExtensionsPath = C:\Program Files (x86)\MSBuild
        MSBuildExtensionsPath32 = C:\Program Files (x86)\MSBuild
        MSBuildExtensionsPath64 = C:\Program Files\MSBuild
    i changed mine tho MSBuildExtensionsPath32=C:\Program Files (x86)\Microsoft Visual Studio\year\edition\Common7

**Comment by maptuhec** [comment]
Thanks for the detailed explanation!

**Comment by thepiwo** [comment]
@maptuhec as part of this issue we could maybe add a note about this in the installation documentation.

**Comment by maptuhec** [comment]
@thepiwo yes that was my intention too, that's why I asked Goodness for this great explenation
