### ISSUE TITLE
aeproject epoch --stop not working

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-forgae-js#25]
child of #55

Hey guys, doing $ aeproject epoch --stop returns that it was stopped successfully, although everything just keeps running, you can check with $ docker ps 

Cheers!

**Comment by maptuhec** [comment]
hey @nikita-fuchs  it seems working now, can you please try again with the latest version of **forgae** in npm ?

Thanks

**Comment by nikita-fuchs** [comment]
works ! Thank you guys, good work !
